### ISSUE TITLE
Allow returning HTTP 403 (Forbidden) instead of only 401

### ISSUE THREAD

**Issue by mimetnet** [franciscogouveia/hapi-rbac#25]
It would be great if the "onPostAuth" handler could support returning 403 (Forbidden). This would help API client's distinguish between Authentication and Authorization Failures.

This could be a config option to either hard-code the result for RbacCore.DENY, or allow a function to specify.

I would be more than happy to make the change if you are willing to accept a patch.

Please let me know.

**Comment by franciscogouveia** [comment]
Response code `403` is the correct response code, because it is deciding only about authorization and not about authentication. My terrible mistake :)

I will make it a configurable parameter for the `deny` and `undetermined` cases, with the current default `401` to avoid breaking changes. I will still assign this issue for a future major release, where `403` should become the default.

**Comment by franciscogouveia** [comment]
Version `2.0.1` released. Update your dependencies and check [here](https://github.com/franciscogouveia/hapi-rbac/blob/master/API.md#defining-the-response-code) how to use it.

**Comment by mimetnet** [comment]
Thank you very much @franciscogouveia. This is great!
